🎉 お絵かきキャンバス実装
cat-crosswalk/nascalay-v2 pull request #8
Opened 2024-05-16 13:34 UTC by SSlime-s

ベースは v1 のときのやつ
ガッツリリファクタしたから原型はあんまない
塗りつぶし部分はほぼまんま

端っこで途切れないようにいい感じにした

`localhost:5173/tmp2` でぐりぐりできます

2024-05-17 10:03 UTC, ras0q requested changes
とりあえずfill

2024-05-17 10:03 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
`widthRange[1]`しか使わないなら`xMax`とかにして外側から`xRange[1]`を渡すのがよさそう

2024-05-17 10:03 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  const colorObj = hexToColor(color);
```suggestion
  const color = hexToColor(colorCode);
```
が分かりやすいかも

2024-05-17 10:03 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +      ) ?? x;
今のところ左右分けたい需要なさそうだしdrawHorizonal(ly?)にまとめてもいいかも

2024-05-17 10:03 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  }
ここ読むのちょっと大変だったけどこれをしてるのか (さすがにもう少しいい命名ありそう、思いつかんけど)
![image](https://github.com/cat-crosswalk/nascalay-v2/assets/66677201/557d5c86-5f19-47c1-a4fa-1d486a626cef)

追加されるseedから左右に塗る範囲が特定できるからそこまでseedに含めて返してもよさそう

2024-05-17 10:03 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  likeEqualColor: LikeEqualColor,
likeEqualColorバケツリレーしてるの辛そうだからこっちで誤差10定義しても問題なさそう
ユーザーがここいじることないだろうし

2024-05-17 10:03 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  }
seedって変数名もわかりにくいかも、positionとか

2024-05-17 10:11 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
んー 大差ないように思える (この関数ここでしか使わないし)
widthRange を何も考えずバケツリレーしたほうがわかりやすくないか

2024-05-17 10:11 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  likeEqualColor: LikeEqualColor,
いいっちゃいいけど疎にしたかった

2024-05-17 10:13 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  }
seed fill というアルゴリズムなので seed です

今更だけどアルゴリズム部分は手つけてないから見なくていいよ

2024-05-17 10:14 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +      ) ?? x;
結局 drawHorizonal では drawToLeft と drawToRight を呼ぶわけで変わらないように思える

2024-05-17 10:16 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  const colorObj = hexToColor(color);
変えた あざす

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/features/artboard/useHistory.ts
> +    if (history.current.undoList.length === 0) return null;
実質これと同じだけど`canUndo`を使うのがよさそう
他のとこも

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  likeEqualColor: LikeEqualColor,
まあわかるか

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  }
なるほどね
flood fillの方がメジャーかも？なんでもいいです

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/features/artboard/useArtboard.ts
> +    if (next === null) return;
時間的にnextなのは分かるがprevだろみたいな気もする

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/features/artboard/useArtboard.ts
> +      }
普通に`ctrl+z`でundo/`ctrl+Z`でredoじゃだめかな

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/utils/unreachable.ts
> +}
throwしてるの外から見るとちょいわかりづらいからラップせずに普通にthrowすればよさそう

2024-05-17 10:41 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
配列になってるせいでreadonlyつけないといけなくなってるし厳密には大小チェックとかも入れるべきだから大小が分かってる外側で右端だけ渡す方がいいな

2024-05-17 10:48 UTC, SSlime-s commented on apps/client/app/features/artboard/useHistory.ts
> +    if (history.current.undoList.length === 0) return null;
こっちのほうがコストが低くて安全なので

2024-05-17 10:49 UTC, SSlime-s commented on apps/client/app/utils/unreachable.ts
> +}
どゆこと

2024-05-17 10:50 UTC, ras0q commented on apps/client/app/utils/unreachable.ts
> +}
この関数呼ばずに直接throwすれば良くない？ってことです

2024-05-17 10:51 UTC, SSlime-s commented on apps/client/app/features/artboard/useArtboard.ts
> +      }
こっちの方が読みやすいので (あと多分 Caps lock でバグる)

2024-05-17 10:52 UTC, SSlime-s commented on apps/client/app/features/artboard/useArtboard.ts
> +    if (next === null) return;
次に適用するって意味で next ね

2024-05-17 10:53 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  }
seed fill というアルゴリズムだからというのは若干嘘で、seed を使ったアルゴリズムだから seed fill という名前がついている (実際 flood fill の解説としても seed をつかうはず)

2024-05-17 10:55 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
readonly つけないといけなくなってるってのはおかしくないか つけなくても動くし
んー `type WidthRange = readonly [number, number]` があったとしてそれを渡してるようなもんと考えるとどうですか

2024-05-20 22:45 UTC, SSlime-s commented on apps/client/app/utils/unreachable.ts
> +}
この関数の本質は throw しているところではなく、引数に never を取ってるところで exhaustive check のための関数

関数を介さずに
```
const exhaustive: never = {引数にいれる変数}
throw new Error(`unreachable: ${exhaustive}`)
```

とか書くこともできるけど、こう書くよりも `unreachable(...)` って書いたほうが意味論的にもわかりやすいよねってのがモチベーションなので、こう書きたいです

2024-05-31 07:55 UTC, ras0q reviewed
大体見たつもり

2024-05-31 07:55 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
`drawToRight`で左端を使うことはまずないから右端だけを渡して単純なデータ結合にすればいいのに不必要にスタンプ結合(多分)になっちゃってるのがやっぱりもやってる
そこそこ複雑なオブジェクトのいくつかのプロパティを使うとかならオブジェクトそのまま渡しても許せるんだけど1個しか渡すものがないのでコストが変わらないなら右端だけ渡せばいいじゃん！って思っちゃう

↓とのトレードオフでしかないんだけどこの関数内では左端が影響しないことを関数名だけじゃなくて引数で制御してほしさがある
> widthRange を何も考えずバケツリレーしたほうがわかりやすくないか

2024-05-31 07:55 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +function updateSeeds(
updateSeeds、わかりにくすぎるからあとでいいから変えてね、という主張だけ

2024-05-31 07:55 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  data: Color[][],
```suggestion
  colorMap: Color[][],
```
とか`pixelData`とかだと苦なく読める

2024-05-31 07:55 UTC, ras0q commented on apps/client/app/utils/unreachable.ts
> +}
理解しました

2024-05-31 07:55 UTC, ras0q commented on apps/client/app/features/artboard/useHistory.ts
> +    if (history.current.undoList.length === 0) return null;
コスト周りあまり詳しくないけど例えばcanUndo/canRedoをなくしてhistoryだけをstateで管理するのとかはどう

2024-05-31 07:55 UTC, ras0q commented on apps/client/app/features/artboard/useArtboard.ts
> +      }
理解しました

2024-05-31 07:57 UTC, ras0q commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
#10だとseedの中に全部入れてるのか
そこまでやると許さざるを得なくなってる

2024-05-31 07:58 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +function updateSeeds(
PR 出してるし前言ったけど bucketFill は修正しないね

2024-05-31 07:59 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  widthRange: readonly [number, number],
PR 出してるし前言ったけど bucketFill は修正しないね

2024-05-31 08:06 UTC, SSlime-s commented on apps/client/app/features/artboard/useHistory.ts
> +    if (history.current.undoList.length === 0) return null;
正直書いたの前だからあんまり覚えてないんだけど
history を ref で持ってるのは破壊的変更したほうがコピーのコスト削減できる & 読みやすいから state じゃなくて ref で持って破壊的変更してるはず
リレンダリング的な話だと history の途中 (最初でも最新でもないところ) でリレンダリング走らないからちょっとだけ得
変更し忘れ的な話をしたいんだと思うけど、この hooks 自体が小さいしシンプルだからこっちのほうが良くないかなと思うけど

2024-05-31 08:07 UTC, SSlime-s commented on apps/client/app/features/artboard/bucketFill.ts
> +  data: Color[][],
PR 出してるし前言ったけど bucketFill は修正しないね

向こうでも data 使ってるからそっちに書いてくれ

2024-05-31 08:25 UTC, ras0q approved these changes

2024-05-31 08:25 UTC, ras0q commented on apps/client/app/features/artboard/useHistory.ts
> +    if (history.current.undoList.length === 0) return null;
多重管理してるのがやっぱり気になるけどちょっとでもパフォーマンスいいならこれでもいいです

2024-05-31 08:27 UTC, SSlime-s commented on apps/client/app/features/artboard/useHistory.ts
> +    if (history.current.undoList.length === 0) return null;
ちょっとでもパフォーマンスがいいのは確かだよ (上にも理由書いてるけど)

2024-05-31 09:15 UTC, merged